# GolangCI-Lint configuration for comprehensive code quality checks
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - test-output
    - coverage
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: simulated_exchange
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  gofumpt:
    extra-rules: true
  godox:
    keywords:
      - TODO
      - BUG
      - FIXME
      - HACK
  revive:
    min-confidence: 0.1
    rules:
      - name: var-naming
      - name: package-comments
      - name: dot-imports
      - name: blank-imports
      - name: exported
      - name: var-declaration
      - name: package-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gosec:
    excludes:
      - G404 # Random number generation
    config:
      G301: "0644"
      G302: "0600"
      G306: "0600"

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - revive
    - godox
  disable:
    - maligned  # deprecated
    - interfacer # deprecated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gomnd
    # Exclude known linter issues
    - path: test/
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gomnd
    # Exclude shadow checking on the context variable name
    - text: "shadow: declaration of \"ctx\""
      linters:
        - govet
    # Exclude shadow checking on the error variable name
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Show only new issues: if there are unstaged changes or untracked files
  new: false